# Generated by Django 3.2.4 on 2021-06-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0002_auto_20210604_1027'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_user', to='logapp.user')),
            ],
        ),
    ]
